Repository PushkaraSharma/MCQ_Generator, pull requests merged in 2021-10, with the labels that each got.

#5 added padding in textarea and cta buttons
  static/style.css
Labels: hactoberfest-accepted

#8 Fixed header title css issue
  static/style.css
Labels: hactoberfest, hactoberfest-accepted

#11 chnages in varibales name
  Flask_api.py
  gen_mcq.py
  generate_summary.py
Labels: hacktoberfest, hacktoberfest-accepted

#10 FIXED: change UI components for responsiveness #9
  static/style.css
Labels: hacktoberfest, hacktoberfest-accepted
